baseURL = "https://jaykastudios.com/"

# This is a "one page"-website, so we do not need these kinds of pages...
#disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

enableRobotsTXT = true

defaultContentLanguage = "en"

# The name of this wonderful theme ;-).
theme = "jayka-theme"

# The browser tab name
title = "Jayka Studios"

# In order to add version information in the page's footer set to true.
# enableGitInfo = false

# enable emoji processing in Markdown (valid only for pure markdown content)
enableEmoji = true

[markup.goldmark.renderHooks.image]
   enableDefault = true

[[module.mounts]]
   source = 'assets'
   target = 'assets'
[[module.mounts]]
   source = 'static'
   target = 'assets'
   
# Theme-specific variables `.Site.Params.myParamName`
[params]

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and https://gohugo.io/templates/internal#open-graph.
    # NOT the actual header background image, go to _index.md instead
    images = ["images/og_image_1200x630.png"]

    # When set true, it creates a visual guard (partially transparent rounded box), preventing non-ideal background images from interfering with title/description headings
    # Ideal images are homogenous around the centre and contrasting to the text.
    # see CSS classes: .title-and-description-guard, .blog-title, .blog-description
    # see _index.md header_headline and header_subheadline
    title_guard = false

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Jayka Studios"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Crafting experimental unique games."

    # Show a menu of languages available
    language_menu = false

    # Show also a language menu item for the current language, if false only
    # show the remaining languages
    show_current_lang = false

    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Plain HTML is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© Jayka Studios"

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    hidedesignbyline = true

    # The sections of the home page alternate styling. Mark invert as true to swap the styling of the sections
    invertSectionColors = false

    # Options used for automatic image generation. see: https://gohugo.io/content-management/image-processing/
    image_options = "webp q97 lanczos photo"

    # Use "page_title | site_title" for <title> tags
    # e.g. <title>Legal | Jane Doe - Nutrition Coach & Chef Consultant</title>
    combine_page_and_site_title = false

    [params.footer]
    # Show contact icons for email/phone (if specified) in the footer of the page
    showContactIcons = false

    # Show links indicated with footer_menu and footer_menu_title in the footer of the page
    showFooterLinks = false

    [params.meta]
        keywords = "Counterfeit Bank game, Mobile simulation games,Indie simulation games,Money simulation game,Currency counterfeit simulator,Jayka Studios games,Games inspired by Indian culture,Indie game studios in India,Games about current affairs,Everyday life simulation games,Indian indie games 2025, Best simulation games 2025,Simulation games to play with friends,New mobile simulation games,Strategy games for Android/iOS,Download The Counterfeit Bank game,Try indie simulation games,Create your own money game"

    [[params.contacts]]
        label = "phone"
        value = "+91 9663 904170"
        url = "tel:+91 9663 904170"
        icon = "fa fa-phone"

    [[params.contacts]]
        label = "email"
        value = "business@jaykastudios.com"
        url = "business@jaykastudios.com"
        icon = "fa fa-envelope"

    [[params.contacts]]
        label = "Bluesky"
        value = "jaykastudios.bsky.social"
        url = "https://bsky.app/profile/jaykastudios.bsky.social"
        icon = "fa-brands fa-bluesky"
    
    [[params.contacts]]
        label = "Youtube"
        value = "youtube.com/jaykastudios"
        url = "https://www.youtube.com/@jaykastudios"
        icon = "fa-brands fa-youtube"

    [[params.contacts]]
        label = "Instagram"
        value = "instagram.com/jayka_studios"
        url = "https://www.instagram.com/jayka_studios/"
        icon = "fa-brands fa-instagram"

    [[params.contacts]]
        label = "Facebook"
        value = "facebook.com/Jayka-Studios"
        url = "https://www.facebook.com/people/Jayka-Studios/61580624625952/"
        icon = "fa-brands fa-facebook"

    # Add additional contacts here!
    # [[params.contacts]]
    #     label = ""
    #     value = ""
    #     url = ""
    #     icon = ""


# Define additional languages
[languages]
  [languages.en]
    weight = 10
    languageName = "English"
    contentDir = "content/en"